---
- name: Get PVCs in the namespace
  community.kubernetes.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "netobserv"
  register: pvc_info

- name: Delete PVCs
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      spec: {}
    state: absent
  loop: "{{ pvc_info.resources }}"
  when: pvc_info.resources | length > 0

- name: Delete the namespace netobserv
  community.kubernetes.k8s:
    state: absent
    api: "v1"
    kind: "Namespace"
    name: "netobserv"
...
