---
- name: Install the NetObservability stack
  when:
    - netobserv_action | default(ocp_netobserv_action) == 'install'
  block:
    - name: Pre-run validations
      ansible.builtin.include_tasks: validation.yml

    - name: Set up the NetObservability stack
      ansible.builtin.include_tasks: setup.yml

    - name: Validate cluster the stack
      ansible.builtin.include_tasks: verify.yml

- name: Cleanup NetObservability stack resources
  when:
    - netobserv_action | default(ocp_netobserv_action) == 'cleanup'
  block:
    - name: Cleanup Logging stack resources
      ansible.builtin.include_tasks: cleanup.yml
...
