---
- name: Create the Namespace
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "netobserv"
        labels:
          security.openshift.io/scc.podSecurityLabelSync: "false"
          pod-security.kubernetes.io/enforce: "baseline"
          pod-security.kubernetes.io/enforce-version: "latest"

- name: Setting Object Storage authentication
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: netobserv-loki
        namespace: "netobserv"
      stringData:
        access_key_id: "{{ ocp_netobserv_access_key_id | default(docp_netobserv_access_key_id) }}"
        access_key_secret: "{{ ocp_netobserv_access_key_secret | default(docp_netobserv_access_key_secret) }}"
        bucketnames: "{{ ocp_netobserv_bucket | default(docp_netobserv_bucket) }}"
        endpoint: "{{ ocp_netobserv_endpoint | default(docp_netobserv_endpoint) }}"
        region: "{{ ocp_netobserv_region | default(docp_netobserv_region) }}"

- name: Create the NetObservability Loki Stack
  community.kubernetes.k8s:
    definition:
      apiVersion: loki.grafana.com/v1
      kind: LokiStack
      metadata:
        name: netobserv-loki
        namespace: "netobserv"
      spec:
        size: "{{ ocp_netobserv_loki_size | default(docp_netobserv_loki_size) }}"
        storage:
          schemas:
            - version: v12
              effectiveDate: "{{ ansible_date_time.date }}"
          secret:
            name: netobserv-loki
            type: s3
        storageClassName: "{{ ocp_netobserv_storage_class | default(docp_netobserv_storage_class) }}"
        tenants:
          mode: "openshift-network"

- name: Configuring RBACs
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/rbacs.yml.j2') }}"

- name: Create the Flow Collector
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/flow-collector.yml.j2') }}"
...
