---
- name: Check for config file
  ansible.builtin.stat:
    path: "{{ ocp_netobserv_conf_file }}"
  register: conf_file_stat
  when:
    - ocp_netobserv_conf_file is defined and
      ocp_netobserv_conf_file | length

- name: Fail if config file is not found
  ansible.builtin.fail:
    msg: "Config file {{ ocp_netobserv_conf_file }} not found"
  when: 
    - ocp_netobserv_conf_file is defined and
      ocp_netobserv_conf_file | length
    - conf_file_stat is defined
    - not conf_file_stat.stat.exists

- name: Load the config file
  ansible.builtin.include_vars:
    file: "{{ ocp_netobserv_conf_file }}"
  when:
    - ocp_netobserv_conf_file is defined  and
      ocp_netobserv_conf_file | length
    - conf_file_stat is defined
    - conf_file_stat.stat.exists
 
- name: Get cluster version
  community.kubernetes.k8s_info:
    api: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: cluster_version
  no_log: true

- name: Fail when OCP version is not supported
  vars:
    current_ver_query: "history[?state=='Completed'] | [0].version"
    full_ver: "{{ cluster_version.resources[0].status | json_query(current_ver_query) }}"  # noqa: jinja[invalid]
    current_ver: "{{ full_ver.split('-')[0] }}"
    ocp_version: "{{ current_ver }}"
  ansible.builtin.fail:
    msg: "OCP version must be >= {{ ocp_supported }}"
  when: ocp_version is version( ocp_supported , "<")

- name: Check if the Loki CRD is present
  community.kubernetes.k8s_info:
    kind: CustomResourceDefinition
    name: lokistacks.loki.grafana.com
  register: loki_crd
  no_log: true

- name: Fail if Loki CRD is not present
  ansible.builtin.fail:
    msg: "Loki CRD are not present"
  when: loki_crd.resources | list | count == 0

- name: Check if the Network Observability CRD is present
  community.kubernetes.k8s_info:
    kind: CustomResourceDefinition
    name: flowcollectors.flows.netobserv.io
  register: nob_crd
  no_log: true

- name: Fail if Network Observability CRD is not present
  ansible.builtin.fail:
    msg: "Network Observability CRD is not present"
  when: nob_crd.resources | list | count == 0

- name: Get Storage Classes
  community.kubernetes.k8s_info:
    api_version: v1
    kind: StorageClass
    name: "{{ storage_class | default(ocp_netobserv_storage_class) }}"
  register: sc

- name: Fail when the storage class does not exit
  ansible.builtin.fail:
    msg: "The defined storage class does not exist"
  when:
    - sc.resources | length == 0
...
