---
- name: "Clone opcap repository"  # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ opcap_repo }}"
    dest: "{{ opcap_dir.path }}/opcap"
  register: git_clone_result
  until: git_clone_result is succeeded
  retries: 6
  delay: 10

- name: "Use Golang container to build opcap"
  # Launching a container to build the opcap binary.
  # The directory where the repository has been cloned is bound as a volume.
  # The 'Z' option is for SELinux compatibility.
  command:
    cmd: >
      podman run --name go-builder --rm -it
      --log-level info --pids-limit=0
      -v {{ opcap_dir.path }}/opcap/:/opcap:Z
      golang:1.19 make -C /opcap build OPCAP_VERSION={{ opcap_version }}
  register: opcap_build
  retries: 4
  delay: 10
  until: opcap_build is not failed

- name: "Check opcap bin"
  ansible.builtin.command:
    cmd: >
      ./bin/opcap version
    chdir: "{{ opcap_dir.path }}/opcap"
...
