---

name: DCI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  dci-job:
    name: "DCI Job"
    runs-on: bos2
    steps:

      - name: Add a dci-check-change job to the queue
        run: |
          set -x
          URL="${{ github.event.pull_request._links.self.href }}"
          if curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" "${URL}/files"|jq -r .[].filename|grep -v '\.md$'|grep -E 'roles/|plugins/'; then
            dci-check-change --silent ${{ github.event.pull_request.html_url }}
          else
            echo "No code change"
          fi

...
